name: Bug Report
description: Report a bug or issue with Orb
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the information below to help us resolve the issue.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Run command '...'
        2. Enter '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Orb Version
      description: What version of Orb are you running? (run `orb --version`)
      placeholder: "v1.0.0"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - Linux
        - macOS
        - Windows
        - Other
    validations:
      required: true

  - type: input
    id: os-version
    attributes:
      label: OS Version
      description: "Examples: Ubuntu 22.04, macOS 13.0, Windows 11"
      placeholder: "Ubuntu 22.04"

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component is affected?
      options:
        - CLI (share/connect commands)
        - Relay Server
        - TUI File Browser
        - Cryptography
        - Network/Tunnel
        - Documentation
        - Other

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Please paste relevant log output if available
      render: shell

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here

  - type: checkboxes
    id: terms
    attributes:
      label: Security
      description: Please confirm this is not a security vulnerability
      options:
        - label: This is not a security vulnerability (if it is, please email security@orb.example.com instead)
          required: true
